---
#create directory
- name: create backend directory
  become: true
  file:
    path: ~/backend
    state: directory

#copy to directory
- name: copy backend files
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/artifact.tar.gz

#unpack and remove t
- name: unpack backend files
  become: true
  shell: |
    cd ~/backend
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz

#start BE up
- name: start app
  become: true
  shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
